# Generated by Django 3.1.3 on 2023-06-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
    ]
